"""Distribution packaging for audiobook-ish outputs.

Two formats are supported:

* **M4B** (MPEG-4 audio with chapter markers) — single-file audiobook for
  phones and audiobook apps. Uses ffmpeg to re-encode the existing
  ``audiobook.mp3`` to AAC and embeds an ffmetadata chapter file derived
  from ``manifest.json``. Result is a much smaller, navigable audiobook
  that Apple Books, VLC, Smart AudioBook Player, etc. all recognise.
* **ZIP** (synced web bundle) — packs the player + audio + page images
  into a single archive. Unzip anywhere and open ``player.html``.

Both readers consult ``manifest.json`` so the existing build folder is
the only required input.
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import tempfile
import zipfile
from pathlib import Path

from . import AudiobookIshError
from .combine import find_ffmpeg

log = logging.getLogger(__name__)

DEFAULT_M4B_BITRATE = "64k"

_ZIP_INCLUDE_FILES: tuple[str, ...] = (
    "audiobook.mp3",
    "manifest.json",
    "manifest.js",
    "player.html",
    "player.css",
    "player.js",
)


def _read_manifest(output_dir: Path) -> dict:
    manifest_path = output_dir / "manifest.json"
    if not manifest_path.is_file():
        raise AudiobookIshError(f"manifest.json not found in {output_dir}")
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def build_ffmeta(manifest: dict) -> str:
    """Return ffmpeg metadata text with global tags and chapter markers.

    The output is suitable for ``ffmpeg -i src.mp3 -i ffmeta.txt
    -map_metadata 1 -map_chapters 1 ...``.
    """
    title = manifest.get("source_pdf") or "Audiobook"
    voice = manifest.get("voice") or ""
    speed = manifest.get("speed")
    lines: list[str] = [
        ";FFMETADATA1",
        f"title={title}",
        "genre=Audiobook",
        f"comment=Generated by audiobook-ish (voice={voice}, speed={speed})",
    ]

    duration_sec = float(manifest.get("duration_sec") or 0.0)
    raw_chapters = list(manifest.get("chapters") or [])
    chapters: list[dict] = [
        c for c in raw_chapters
        if isinstance(c.get("start_sec"), (int, float))
    ]
    chapters.sort(key=lambda c: float(c["start_sec"]))

    # If the first chapter doesn't start at 0, prepend an "Intro" marker so
    # the opening minutes are still navigable.
    if chapters and float(chapters[0]["start_sec"]) > 1.0:
        chapters = [{"title": "Intro", "start_sec": 0.0}, *chapters]

    for i, ch in enumerate(chapters):
        start_ms = int(round(float(ch["start_sec"]) * 1000))
        if i + 1 < len(chapters):
            end_ms = int(round(float(chapters[i + 1]["start_sec"]) * 1000)) - 1
        else:
            end_ms = int(round(duration_sec * 1000))
        if end_ms <= start_ms:
            end_ms = start_ms + 1
        ch_title = str(ch.get("title") or f"Chapter {i + 1}").strip()
        if not ch_title:
            ch_title = f"Chapter {i + 1}"
        lines.extend([
            "",
            "[CHAPTER]",
            "TIMEBASE=1/1000",
            f"START={start_ms}",
            f"END={end_ms}",
            f"title={ch_title}",
        ])

    return "\n".join(lines) + "\n"


def package_m4b(
    output_dir: Path,
    dest_m4b: Path,
    bitrate: str = DEFAULT_M4B_BITRATE,
    ffmpeg_path: str | None = None,
) -> None:
    """Build a single ``.m4b`` audiobook from a finished output folder.

    Reads ``audiobook.mp3`` and ``manifest.json`` in ``output_dir``,
    re-encodes the audio to AAC at ``bitrate``, and writes ``dest_m4b``
    with embedded chapter markers.
    """
    output_dir = Path(output_dir)
    dest_m4b = Path(dest_m4b)
    mp3 = output_dir / "audiobook.mp3"
    if not mp3.is_file():
        raise AudiobookIshError(f"audiobook.mp3 not found in {output_dir}")

    manifest = _read_manifest(output_dir)
    ffmeta_text = build_ffmeta(manifest)
    ffmpeg = ffmpeg_path or find_ffmpeg()
    dest_m4b.parent.mkdir(parents=True, exist_ok=True)

    fd, name = tempfile.mkstemp(suffix=".ffmeta", prefix="audiobook_ish_")
    os.close(fd)
    ffmeta_path = Path(name)
    ffmeta_path.write_text(ffmeta_text, encoding="utf-8")

    try:
        cmd = [
            ffmpeg,
            "-y",
            "-hide_banner",
            "-loglevel", "error",
            "-i", mp3.as_posix(),
            "-i", ffmeta_path.as_posix(),
            "-map_metadata", "1",
            "-map_chapters", "1",
            "-c:a", "aac",
            "-b:a", bitrate,
            "-movflags", "+faststart",
            "-f", "mp4",
            dest_m4b.as_posix(),
        ]
        log.info("Packaging %s -> %s @ %s", mp3, dest_m4b, bitrate)
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            tail = (result.stderr or result.stdout or "").strip()[-500:]
            raise AudiobookIshError(f"ffmpeg failed (exit {result.returncode}): {tail}")
    finally:
        try:
            ffmeta_path.unlink()
        except OSError:
            pass


def package_zip(
    output_dir: Path,
    dest_zip: Path,
    include_pages: bool = True,
) -> None:
    """Bundle ``output_dir`` into a single ``.zip`` for sharing/sideloading.

    Includes the player files, MP3, manifest, ``pages/`` (optional), and
    ``assets/``. Excludes ``sentences/`` and ``sentences.json`` because
    those are only needed for resumable synthesis, not playback.

    The archive contains a top-level folder named after the zip's stem,
    so unzipping doesn't litter the destination.
    """
    output_dir = Path(output_dir)
    dest_zip = Path(dest_zip)
    if not output_dir.is_dir():
        raise AudiobookIshError(f"Output directory not found: {output_dir}")
    dest_zip.parent.mkdir(parents=True, exist_ok=True)

    root_name = dest_zip.stem or "audiobook"
    written = 0

    def _add(zf: zipfile.ZipFile, src: Path, arc: str) -> None:
        nonlocal written
        zf.write(src, arcname=f"{root_name}/{arc}")
        written += 1

    # ZIP_STORED: MP3 / PNG are already compressed, and storing avoids
    # spending CPU on data that can't shrink further.
    with zipfile.ZipFile(dest_zip, "w", compression=zipfile.ZIP_STORED, allowZip64=True) as zf:
        for name in _ZIP_INCLUDE_FILES:
            src = output_dir / name
            if src.is_file():
                _add(zf, src, name)
        if include_pages:
            pages_dir = output_dir / "pages"
            if pages_dir.is_dir():
                for png in sorted(pages_dir.glob("*.png")):
                    _add(zf, png, f"pages/{png.name}")
        assets = output_dir / "assets"
        if assets.is_dir():
            for child in sorted(assets.rglob("*")):
                if child.is_file():
                    rel = child.relative_to(output_dir).as_posix()
                    _add(zf, child, rel)

    if written == 0:
        # Nothing recognisable was found: surface a useful error.
        dest_zip.unlink(missing_ok=True)
        raise AudiobookIshError(
            f"Refused to write empty zip; {output_dir} had no recognised audiobook artefacts."
        )
